sudo: false # Enable container-based infrastructure

language: c

# cache: apt # Enable caching on APT when it is available for our repo

os:
    - linux
    - osx

compiler:
    - clang
    - gcc

branches:
    only:
        - master
        - dev-master

env:
    - CCNL_HOME="/home/travis/build/cn-uofbasel/ccn-lite" PATH=$PATH:"$CCNL_HOME/bin":"/home/travis/.local/bin"

addons:
    apt:
        packages:
            - libssl-dev
            - build-essential
            - gcc-avr
            - avr-libc
            - python-pip
#            - linux-headers-$(uname -r)

install:
    # Install dependencies for Arduino compilation
    - wget http://downloads.arduino.cc/arduino-1.0.6-linux64.tgz
    - tar xf arduino-1.0.6-linux64.tgz
    - export ARDUINO_HOME="`pwd`/arduino-1.0.6"
    - export PATH=$PATH:"$ARDUINO_HOME"
    - git clone https://github.com/Seeed-Studio/Ethernet_Shield_W5200.git "$ARDUINO_HOME/libraries/EthernetShieldW5200"
    - git clone https://github.com/Seeed-Studio/WiFi_Shield.git "$ARDUINO_HOME/libraries/WiFiShield"
    #- pip install --user jinja2 pyserial configobj ordereddict argparse glob2
    - pip install --user ino

script:
    # Run build-test.sh
    # Ideally, build-test should be run without specifying the targets.
    # However, bt-lnxkernel, bt-demo-cisco2015, bt-nfn-ccnx2015, bt-nfn-cisco2015 removed because they fail
    - cd $CCNL_HOME/src
    - make clean
    - ./build-test.sh VERBOSE=1 echo-cores bt-relay bt-all bt-pkt bt-omnet bt-demo-ccnb bt-demo-ccnx2015 bt-demo-iot2014 bt-demo-ndn2013 bt-nfn-ccnb bt-nfn-iot2014 bt-nfn-ndn2013


    # Build Arduino (should be merged into build-test eventually)
    - cd $CCNL_HOME/src/arduino

    - cp src-ethernet.ino src/src.ino
    - make clean all BOARD=atmega328 2>&1 | tee /tmp/bt-arduino-ethernet-atmega328.log | sed 's! -\(mmcu\|[fID]\)[a-zA-Z0-9/=_]\+!!g'
    - make clean all BOARD=uno 2>&1 | tee /tmp/bt-arduino-ethernet-atmega328.log | sed 's! -\(mmcu\|[fID]\)[a-zA-Z0-9/=_]\+!!g'

    - cp src-wifly.ino src/src.ino
    - make clean all BOARD=atmega328 2>&1 | tee /tmp/bt-arduino-ethernet-atmega328.log | sed 's! -\(mmcu\|[fID]\)[a-zA-Z0-9/=_]\+!!g'
    - make clean all BOARD=uno 2>&1 | tee /tmp/bt-arduino-ethernet-atmega328.log | sed 's! -\(mmcu\|[fID]\)[a-zA-Z0-9/=_]\+!!g'
