language: c

os:
        - linux
        - osx

env:
        - USE_NFN=1 CCNL_HOME="/home/travis/build/cn-uofbasel/ccn-lite" PATH=$PATH:"$CCNL_HOME/bin"
        # Add USE_NACK when fixed

compiler:
        - clang
        - gcc

branches:
        only:
                - master
                - dev-master

install:
        - sudo apt-get update -y
        - sudo apt-get install -y libssl-dev build-essential
#        - sudo apt-get install linux-headers-$(uname -r)

script:
        - cd $CCNL_HOME/src

        # Run build-test.sh
        - make clean
        - ./build-test.sh echo-cores bt-relay bt-all bt-pkt # Remove arguments when bt-lnxkernel compiles

        # Build again for test scripts
        - make clean
        - make -j8 all

        # Run all demo relay test scripts
        - cd $CCNL_HOME/test/scripts
        - ./demo-relay.sh ccnb udp false
        - ./demo-relay.sh ccnb ux false
        - ./demo-relay.sh ccnx2015 udp false
        - ./demo-relay.sh ccnx2015 ux false
#        - ./demo-relay.sh cisco2015 udp false #Reenable if cisco format is fixed
#        - ./demo-relay.sh cisco2015 ux false #Reenable if cisco format is fixed
        - ./demo-relay.sh iot2014 udp false
        - ./demo-relay.sh iot2014 ux false
        - ./demo-relay.sh ndn2013 udp false
        - ./demo-relay.sh ndn2013 ux false

        # Run nfn_test script
        - cd $CCNL_HOME/test/scripts/nfn
        - ./nfn_test.sh #Reenable ccnx, cisco format is fixed
