language: C


compiler: 
        - clang
        - gcc

os:
        - linux
        - osx

branches:
        only:
                - master
                - dev-master

install:
        - sudo apt-get update 
        - sudo apt-get install -y libssl-dev

script:
        - cd src 
        - make clean all 
        - cd -

after_success:
        - cd ./test/scripts/nfn
        - sh nfn_test.sh
        - cd -
