language: C


compiler: 
        - clang
        - gcc

os:
        - linux
        - osx

branches:
        only:
                - master
                - dev-master

before_install:
        sudo apt-get update && sudo apt-get install -y libssl-dev

script:
        cd src && make clean all && cd -
