language: C


compiler: 
        - clang
        - gcc

os:
        - linux
        - osx

branches:
        only:
                - master
                - dev-master

install:
        - sudo apt-get update -y 
        - sudo apt-get install -y libssl-dev build-essential

script:
        - cd src 
        - ./build-test.sh
        - cd -
